FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /source

# install dotnet AOT dependencies
RUN apk add clang build-base zlib-dev

COPY . .
RUN dotnet publish -r linux-musl-x64 -c Release -o /app CloseAsteroids.csproj

FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0-alpine
WORKDIR /app
COPY --from=build /app .
ENV ASTEROIDARGS="--date-min=2099-12-25 --date-max=2100-01-01 --dist-max=0.2 --body=Mercury"
USER $APP_UID
ENTRYPOINT /app/CloseAsteroids $ASTEROIDARGS